"""
    verify_chksums - compares two files generated by 'batch-md5'.

    Copyright (C) 2025  IcePanorama

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import sys
import logging
from checksum_dict import ChecksumDict

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG,
                        format='[%(levelname)s] %(message)s')

    if len(sys.argv) < 3:
        logging.error(f"Invalid usage error. Try: {sys.argv[0]} "
                      + "path_to_original.txt path_to_alt.txt`")
        exit(1)

    try:
        original = ChecksumDict(sys.argv[1])
        alt = ChecksumDict(sys.argv[2])

        if (original == alt):
            logging.info("All checksums match... exiting.")
            exit(0)
    except (RuntimeError, ChecksumDict.ChecksumMismatchError) as e:
        logging.error(e)
        exit(1)
