"""
    verify_chksums.py
    Compares two files generated by `batch_md5.sh`.
"""

import sys

if __name__ == "__main__":
    if len(sys.argv) < 3:
        raise ValueError(f"Invalid usage error. Try: `{
                         sys.argv[0]} path_to_original.txt path_to_alt.txt`")

    original = {}  # key: path string, val: checksum value
    with open(sys.argv[1]) as f:
        for line in f:
            segments = line.split(" ")
            assert (len(segments) >= 2)
            original[segments[1]] = segments[0]

    # TODO: finish this.

    alt = {}
