#ifndef _ISO_9660_FILE_SYSTEM_VOLUME_DESCRIPTOR_TYPE_CODE_H_
#define _ISO_9660_FILE_SYSTEM_VOLUME_DESCRIPTOR_TYPE_CODE_H_

/** See: https://wiki.osdev.org/ISO_9660#Volume_Descriptor_Type_Codes. */
typedef enum _VolDescTypeCode_e
{
  _VDTC_BOOT_RECORD,
  _VDTC_PRIMARY_VOLUME,
  _VDTC_SUPPLEMENTARY_VOL,
  _VDTC_VOL_PARTITION,
  _VDTC_VOL_DESC_SET_TERMINATOR = 255
} _VolDescTypeCode_t;

#endif /* _ISO_9660_FILE_SYSTEM_VOLUME_DESCRIPTOR_TYPE_CODE_H_ */
